
version: 1.2.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Ubuntu1804
shallow_clone: true
services:
- docker
build_script:
- pwsh: docker build -t besttrace:${env:APPVEYOR_BUILD_VERSION} .